package jiyun.com.openresausechina.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jiyun.com.openresausechina.model.AutoLogin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig autoLoginDaoConfig;

    private final AutoLoginDao autoLoginDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        autoLoginDaoConfig = daoConfigMap.get(AutoLoginDao.class).clone();
        autoLoginDaoConfig.initIdentityScope(type);

        autoLoginDao = new AutoLoginDao(autoLoginDaoConfig, this);

        registerDao(AutoLogin.class, autoLoginDao);
    }
    
    public void clear() {
        autoLoginDaoConfig.clearIdentityScope();
    }

    public AutoLoginDao getAutoLoginDao() {
        return autoLoginDao;
    }

}
